### ISSUE TITLE
스프링 프로젝트 초기 설정

### ISSUE THREAD

**Issue by toneofrain** [toneofrain/pawwow-server#1]
## Description
- 스프링 프로젝트 초기 설정

## Todo
- [ ] Spring initializr
- [ ] prod, local, dev profile별 application properties 설정
- [ ] jpa/querdsl configuration
- [ ] lombok configuration
- [ ] redis configuration
- [ ] kafka configuration
- [ ] mail/thymeleaf/jwt configuration
- [ ] swagger configuratin
- [ ] async configuration
- [ ] spring scheduler configuration
