### ISSUE TITLE
깃허브 초기 설정

### ISSUE THREAD

**Issue by toneofrain** [toneofrain/pawwow-server#2]
## Description
프로젝트 진행을 위한 깃허브 초기 설정을 진행

## Todo
- [x] 이슈 템플릿 추가
- [x] 이슈 라벨 추가
- [x] PR 템플릿 추가
- [x] 인텔리제이 깃허브 이슈 연동
- [x] 깃허브 액션 기본 설정 

## References
- [Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [GitHub Actions 빠른 시작](https://docs.github.com/ko/actions/quickstart)
