### ISSUE TITLE
깃허브 초기 설정

### ISSUE THREAD

**Issue by toneofrain** [toneofrain/pawwow-server#3]
## Description
프로젝트 진행과 github actions를 위한 깃허브 초기 설정

## Todo
- [x] 브랜치 설정
- [x] 이슈, PR 템플릿, 라벨 작성
- [x] actions secret 설정
- [x] actions 초기 workflow 작성

## References
