### ISSUE TITLE
스프링 프로젝트 초기 구성

### ISSUE THREAD

**Issue by toneofrain** [toneofrain/pawwow-server#8]
## Description
개발 및 빌드를 위한 스프링 프로젝트 초기 구성

## Todo
- [ ] spring initializr로 프로젝트 생성 및 의존성 추가
- [ ] 기타 의존성 추가
- [ ] application properties 설정
- [ ] 빌드용 도커파일 작성
- [ ] jpa, querydsl configuration
- [ ] redis configuration
- [ ] kafaka configuration
- [ ] async, scheduling configuration
- [ ] mail, thymeleaf, jwt configuration

## References
-
